### ISSUE TITLE
Will not compile with gcc 7.2.0

### ISSUE THREAD

**Issue by jrincayc** [city41/ardynia#1]
With gcc 7.2.0 it has the error:
```
sketch/src/loadEntity.cpp: In function 'loadEntity(Entity&, unsigned char) [clone .part.0]':
sketch/src/entityTemplates.h:49:23: error: variable 'entityProperties' with dynamic initialization put into program memory area
 const uint8_t PROGMEM entityProperties[NUM_ENTITIES * NUM_ENTITY_PROPS] = {
                       ^
lto-wrapper: fatal error: /usr/bin/avr-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/avr/7.2.0/../../../../avr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Leonardo.
```

**Comment by city41** [comment]
How are you compiling Arduboy sketches with gcc 7.2.0? The Arduino IDE ships with gcc 5.4.0. I'm not sure I can support anything beyond that to be honest, as that is the standard for Arduboy and Arduino in general. I don't have any experience with avr outside of those realms.

Are you able to compile using the Arduino IDE?

**Comment by jrincayc** [comment]
I am using Arduino 1.8.5 on Fedora which uses gcc 7.2.0 which doesn't work.  I am curious if you get a warning with gcc 5.4.0, or if that line compiles cleanly.  I'm actually a bit mystified by the error since I am not seeing why gcc thinks there should be dynamic initialization since it seems to be a const initialized by constexpr's.

**Comment by selb** [comment]
`widthAndHeight(0, 0)` in the sunken bridge definition is the non-constant expression. Newer avr-gcc seems to consider `(width - 1)` undefined because the constant `1` is signed (or something along those lines: I couldn't find any way to get avr-gcc to emit an actually helpful error). Clarifying that unsigned wraparound is desired by making that constant unsigned fixes it:

```diff
diff --git a/src/entityTemplates.h b/src/entityTemplates.h
index 678879c..f0ada8c 100644
--- a/src/entityTemplates.h
+++ b/src/entityTemplates.h
@@ -36,7 +36,7 @@ const uint8_t NUM_ENTITY_POINTERS = 3;
  * it first subtracts one from the value. When unpacking, need to add 1 back on
  */
 constexpr uint8_t widthAndHeight(uint8_t width, uint8_t height) {
-    return (width - 1) << 4 | (height - 1);
+    return (width - 1u) << 4 | (height - 1u);
 }
 
 /**
```

I'm also on Fedora and avr-gcc 7.2.0, and can confirm that this is the only change needed to build in that environment.

**Comment by city41** [comment]
excellent, thanks @selb! I'll go ahead and fix that in the code right now.

**Comment by city41** [comment]
Going to close this assuming it's fixed, can always reopen if needed.

**Comment by jrincayc** [comment]
Yes, it is fixed.  Thank you.
